site_name: GateChain Doc
site_description: GateChain Documents
site_author: GateChain Team
site_url: "" 
site_dir: /home/docs/en       


nav:
  - Home: 
    - Overview: index.md
    - Ecosystem: home/ecosystem.md
    - Application: home/application.md
    - EVM: home/evm.md
    - Academic Research: home/academic-research.md
    - Terms: home/terms.md
    - Quick Start: home/quick-start.md
    - Advanced Docs: home/advanced-docs.md
  - GateChain:
    - Concepts:
      - Account system: gatechain/concepts/account.md
      - Revocable Tx: gatechain/concepts/revocable-tx.md
      - Delay Arrival: gatechain/concepts/delay.md
    - Asset: gatechain/gatechain-asset.md
    - MultiSig: gatechain/gatechain-multisig.md
    - Security: gatechain/gatechain-security.md
    - PoS: gatechain/gatechain-pos.md
    #- EVM: gatechain/evm.md
    - Academic Research: gatechain/gatechain-research.md
    - GateScan: gatechain/explorer.md
    - Facuet: gatechain/facuet.md
  - Developers:
    - Deploy: developers/gatechain-build.md
    - PoS: developers/gatechain-pos.md
    - CLI: 
      - Overview: developers/cli/README.md
      - Standard Account: developers/cli/account.md
      - Consensus Account: developers/cli/con-account.md
      - Vault Account: developers/cli/vault-account.md
      - Block: developers/cli/block.md
      - Transaction Tx: developers/cli/tx.md
      - Revocable Tx: developers/cli/revocable-tx.md
      - Token: developers/cli/token.md
      - Foundation: developers/cli/foundation.md
      - Staking: developers/cli/staking.md
      - Distribution: developers/cli/distribution.md
    - API:
      - Overview: developers/api/README.md
      - Standard Account: developers/api/account.md
      - Consensus Account: developers/api/con-account.md
      - Vault Account: developers/api/vault-account.md
      - Block: developers/api/block.md
      - Transaction Tx: developers/api/tx.md
      - Revocable Tx: developers/api/revocable-tx.md
      - Token: developers/api/token.md
      - Foundation: developers/api/foundation.md
      - Staking: developers/api/staking.md
      - Distribution: developers/api/distribution.md
    - EVM_RPC: developers/json-rpc.md
    - Web3JS: https://web3js.readthedocs.io/en/v1.2.11/
  - Integration:
    - RPC node: integration/rpc-node-list.md
    - Exchange: integration/gatechain-platform.md
    - GateSwap: integration/gateswap.md
    - GateBridge: integration/gatebridge.md
    - Issue Token: integration/issuetoken.md
    - Tools:
      - MetaMask: integration/tool-metamask.md
      - Remix: integration/tool-remix.md
      - Truffle: integration/tool-truffle.md
    - Wallet: integration/gatechain-wallet.md
  - FAQ:
    - More Help: faq/README.md








dev_addr: 127.0.0.1:4051
copyright: Copyright 2019-2020, All Rights Reserved

theme:
  language: en
  name: material
  logo: images/GT.png
  custom_dir: overrides
  favicon: images/GT.png
  palette:
    - scheme: default
      primary: Blue Grey
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: Blue Grey
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
  #palette:
    #primary: 'Blue Grey'
    #accent: 'red'
    #scheme: default
    #toggle:
     # icon: material/toggle-switch-off-outline
     # name: Switch to dark mode
    #scheme: slate
    #toggle:
      #icon: material/toggle-switch
     # name: Switch to light mode
  #features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    #- navigation.top
    #- toc.integrate


extra_css:
- 'stylesheets/extra.css'
# - 'config/css/custom.css'

extra_javascript:
  - 'javascripts/extra.js'
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  search:
    language: 'jp, en'
  alternate:
    - name: English
      link: ./
      lang: en

    - name: 中文简体
      link: ../
      lang: zh

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
